#ifdef CAGE_PREFIX
#define add_frame cage_add_frame
#define add_frames cage_add_frames
#define add_vec cage_add_vec
#define animate_sprite cage_animate_sprite
#define animation cage_animation
#define animation_mode cage_animation_mode
#define append_event cage_append_event
#define append_events cage_append_events
#define back_ease_in cage_back_ease_in
#define back_ease_in_out cage_back_ease_in_out
#define back_ease_out cage_back_ease_out
#define bbox_in_bbox cage_bbox_in_bbox
#define bbox_intersect cage_bbox_intersect
#define blend_mode cage_blend_mode
#define bounce_ease_in cage_bounce_ease_in
#define bounce_ease_in_out cage_bounce_ease_in_out
#define bounce_ease_out cage_bounce_ease_out
#define circular_ease_in cage_circular_ease_in
#define circular_ease_in_out cage_circular_ease_in_out
#define circular_ease_out cage_circular_ease_out
#define cleanup_font cage_cleanup_font
#define cleanup_image cage_cleanup_image
#define cleanup_sound cage_cleanup_sound
#define cleanup_sprite cage_cleanup_sprite
#define cleanup_timeline cage_cleanup_timeline
#define clear_image cage_clear_image
#define color cage_color
#define color_from_RGB cage_color_from_RGB
#define color_from_RGBA cage_color_from_RGBA
#define coords cage_coords
#define create_animation cage_create_animation
#define create_blank_image cage_create_blank_image
#define create_font cage_create_font
#define create_image cage_create_image
#define create_sound cage_create_sound
#define create_sprite cage_create_sprite
#define create_target_image cage_create_target_image
#define create_timeline cage_create_timeline
#define cubic_ease_in cage_cubic_ease_in
#define cubic_ease_in_out cage_cubic_ease_in_out
#define cubic_ease_out cage_cubic_ease_out
#define destroy_animation cage_destroy_animation
#define destroy_font cage_destroy_font
#define destroy_image cage_destroy_image
#define destroy_sound cage_destroy_sound
#define destroy_sprite cage_destroy_sprite
#define destroy_timeline cage_destroy_timeline
#define div_vec cage_div_vec
#define draw_image cage_draw_image
#define draw_on_image cage_draw_on_image
#define draw_on_screen cage_draw_on_screen
#define draw_sprite cage_draw_sprite
#define draw_sprite_frame cage_draw_sprite_frame
#define draw_text cage_draw_text
#define elastic_ease_in cage_elastic_ease_in
#define elastic_ease_in_out cage_elastic_ease_in_out
#define elastic_ease_out cage_elastic_ease_out
#define error_msg cage_error_msg
#define exit_with_error_msg cage_exit_with_error_msg
#define exponential_ease_in cage_exponential_ease_in
#define exponential_ease_in_out cage_exponential_ease_in_out
#define exponential_ease_out cage_exponential_ease_out
#define file_spec cage_file_spec
#define font cage_font
#define frame cage_frame
#define game_loop cage_game_loop
#define game_setup_and_loop cage_game_setup_and_loop
#define game_state cage_game_state
#define get_error_msgs cage_get_error_msgs
#define get_image_alpha cage_get_image_alpha
#define get_screen_size cage_get_screen_size
#define get_window_size cage_get_window_size
#define hdg_vec cage_hdg_vec
#define image cage_image
#define init_image_from_file cage_init_image_from_file
#define init_timeline cage_init_timeline
#define interpolate cage_interpolate
#define is_file_exists cage_is_file_exists
#define is_playing cage_is_playing
#define key_down cage_key_down
#define key_pressed cage_key_pressed
#define keyboard cage_keyboard
#define linear_interpolation cage_linear_interpolation
#define load_font cage_load_font
#define load_sound cage_load_sound
#define lock_image cage_lock_image
#define measure_text cage_measure_text
#define mouse cage_mouse
#define mul_vec cage_mul_vec
#define norm_vec cage_norm_vec
#define pause_timeline cage_pause_timeline
#define pixels_collide cage_pixels_collide
#define play_animation cage_play_animation
#define play_sound cage_play_sound
#define point_in_bbox cage_point_in_bbox
#define prepare_sprite cage_prepare_sprite
#define quadratic_ease_in cage_quadratic_ease_in
#define quadratic_ease_in_out cage_quadratic_ease_in_out
#define quadratic_ease_out cage_quadratic_ease_out
#define quartic_ease_in cage_quartic_ease_in
#define quartic_ease_in_out cage_quartic_ease_in_out
#define quartic_ease_out cage_quartic_ease_out
#define quintic_ease_in cage_quintic_ease_in
#define quintic_ease_in_out cage_quintic_ease_in_out
#define quintic_ease_out cage_quintic_ease_out
#define read_file cage_read_file
#define rect_from_sub_bbox cage_rect_from_sub_bbox
#define rectangle cage_rectangle
#define relax_screen cage_relax_screen
#define reset_timeline cage_reset_timeline
#define screen cage_screen
#define screen_color cage_screen_color
#define set_blend_mode cage_set_blend_mode
#define set_image_alpha cage_set_image_alpha
#define set_screen_size cage_set_screen_size
#define set_volume cage_set_volume
#define set_window_size cage_set_window_size
#define settings cage_settings
#define shake_screen cage_shake_screen
#define sine_ease_in cage_sine_ease_in
#define sine_ease_in_out cage_sine_ease_in_out
#define sine_ease_out cage_sine_ease_out
#define sound cage_sound
#define sprite cage_sprite
#define stop_animation cage_stop_animation
#define stop_sound cage_stop_sound
#define sub_vec cage_sub_vec
#define swap_vecs cage_swap_vecs
#define timeline cage_timeline
#define timeline_event cage_timeline_event
#define toolbox cage_toolbox
#define translate_bbox cage_translate_bbox
#define unit_vec cage_unit_vec
#define unlock_image cage_unlock_image
#define update_mouse cage_update_mouse
#define update_timeline cage_update_timeline
#define vec_dist cage_vec_dist
#define vec_dist_mntn cage_vec_dist_mntn
#define vec_dist_sqrd cage_vec_dist_sqrd
#define vec_len cage_vec_len
#define vec_len_sqrd cage_vec_len_sqrd
#define write_file cage_write_file
#define xy_vec cage_xy_vec
#define zero_vec cage_zero_vec
#define ADD CAGE_ADD
#define BLEND CAGE_BLEND
#define FREEZE_LAST_FRAME CAGE_FREEZE_LAST_FRAME
#define LOOP_FRAMES CAGE_LOOP_FRAMES
#define MULTIPLY CAGE_MULTIPLY
#define NONE CAGE_NONE
#define PINGPONG_FRAMES CAGE_PINGPONG_FRAMES
#endif
