#ifdef CAGE_PREFIX
#undef ADD
#undef BLEND
#undef FREEZE_LAST_FRAME
#undef LOOP_FRAMES
#undef MULTIPLY
#undef NONE
#undef PINGPONG_FRAMES
#undef add_frame
#undef add_frames
#undef add_vec
#undef animate_sprite
#undef animation
#undef animation_mode
#undef append_event
#undef append_events
#undef back_ease_in
#undef back_ease_in_out
#undef back_ease_out
#undef bbox_in_bbox
#undef bbox_intersect
#undef blend_mode
#undef bounce_ease_in
#undef bounce_ease_in_out
#undef bounce_ease_out
#undef circular_ease_in
#undef circular_ease_in_out
#undef circular_ease_out
#undef cleanup_font
#undef cleanup_image
#undef cleanup_sound
#undef cleanup_sprite
#undef cleanup_timeline
#undef clear_image
#undef color
#undef color_from_RGB
#undef color_from_RGBA
#undef coords
#undef create_animation
#undef create_blank_image
#undef create_font
#undef create_image
#undef create_sound
#undef create_sprite
#undef create_target_image
#undef create_timeline
#undef cubic_ease_in
#undef cubic_ease_in_out
#undef cubic_ease_out
#undef destroy_animation
#undef destroy_font
#undef destroy_image
#undef destroy_sound
#undef destroy_sprite
#undef destroy_timeline
#undef div_vec
#undef draw_image
#undef draw_on_image
#undef draw_on_screen
#undef draw_sprite
#undef draw_sprite_frame
#undef draw_text
#undef elastic_ease_in
#undef elastic_ease_in_out
#undef elastic_ease_out
#undef error_msg
#undef exit_with_error_msg
#undef exponential_ease_in
#undef exponential_ease_in_out
#undef exponential_ease_out
#undef file_spec
#undef font
#undef frame
#undef game_loop
#undef game_setup_and_loop
#undef game_state
#undef get_error_msgs
#undef get_image_alpha
#undef get_screen_size
#undef get_window_size
#undef hdg_vec
#undef image
#undef init_image_from_file
#undef init_timeline
#undef interpolate
#undef is_file_exists
#undef is_playing
#undef key_down
#undef key_pressed
#undef keyboard
#undef linear_interpolation
#undef load_font
#undef load_sound
#undef lock_image
#undef measure_text
#undef message_box
#undef mouse
#undef mul_vec
#undef norm_vec
#undef pause_timeline
#undef pixels_collide
#undef play_animation
#undef play_sound
#undef point_in_bbox
#undef prepare_sprite
#undef quadratic_ease_in
#undef quadratic_ease_in_out
#undef quadratic_ease_out
#undef quartic_ease_in
#undef quartic_ease_in_out
#undef quartic_ease_out
#undef quintic_ease_in
#undef quintic_ease_in_out
#undef quintic_ease_out
#undef read_file
#undef rect_from_sub_bbox
#undef rectangle
#undef relax_screen
#undef reset_timeline
#undef screen
#undef screen_color
#undef set_blend_mode
#undef set_image_alpha
#undef set_screen_blend_mode
#undef set_screen_size
#undef set_volume
#undef set_window_size
#undef settings
#undef shake_screen
#undef sine_ease_in
#undef sine_ease_in_out
#undef sine_ease_out
#undef sound
#undef sprite
#undef stop_animation
#undef stop_sound
#undef sub_vec
#undef swap_vecs
#undef timeline
#undef timeline_event
#undef toolbox
#undef translate_bbox
#undef unit_vec
#undef unlock_image
#undef update_mouse
#undef update_timeline
#undef vec_dist
#undef vec_dist_mntn
#undef vec_dist_sqrd
#undef vec_len
#undef vec_len_sqrd
#undef write_file
#undef xy_vec
#undef zero_vec
#endif
